services:
  uttambsolutionslimitedstaffs:
    image: ${DOCKER_REGISTRY-}uttambsolutionslimitedstaffs
    build:
      context: Uttambsolutionslimitedstaffs
      dockerfile: Dockerfile

  uttambsolutionslimitedcustomers:
    image: ${DOCKER_REGISTRY-}uttambsolutionslimitedcustomers
    build:
      context: Uttambsolutionslimitedcustomers
      dockerfile: Dockerfile

